# Generated by Django 5.1.4 on 2024-12-05 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PortfolioHome', '0002_introduction_mainpageimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainpageimage',
            name='image',
            field=models.TextField(),
        ),
    ]
